#pragma once

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 175
#define HOLD_ON_OTHER_KEY_PRESS
#define CHORDAL_HOLD

#define COMBO_TERM 50
#define COMBO_ONLY_FROM_LAYER 0
