#pragma once

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 175
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define FLOW_TAP_TERM 140

#define COMBO_TERM 50
#define COMBO_ONLY_FROM_LAYER 0
